# Generated by Django 4.0.5 on 2022-06-16 01:46

import blog.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='Author',
            field=models.ForeignKey(default=1, on_delete=models.SET(blog.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
